import os
import uuid
import shutil
import logging
from fastapi import APIRouter, File, UploadFile, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from pdf2docx import Converter

router = APIRouter(prefix="/api", tags=["PDF to Word"])

def cleanup_files(*paths):
    """Helper function to safely delete temporary files from disk."""
    for path in paths:
        if path and os.path.exists(path):
            try:
                os.remove(path)
            except Exception:
                pass

def convert_pdf_to_word(input_path: str, output_path: str):
    logging.getLogger('pdf2docx').setLevel(logging.ERROR)
    try:
        cv = Converter(input_path)
        cv.convert(output_path, start=0, end=None)
        cv.close()
    except Exception:
        try:
            cv = Converter(input_path)
            cv.convert(output_path, start=0, end=None, multi_processing=False)
            cv.close()
        except Exception as fallback_error:
            raise RuntimeError(f"Professional layout mapping engine failed: {str(fallback_error)}")

@router.post("/pdf-to-word")
async def api_pdf_to_word(file: UploadFile = File(...), background_tasks: BackgroundTasks = None):
    if not file.filename.lower().endswith('.pdf'):
        raise HTTPException(status_code=400, detail="Only PDF files are supported for Word conversion.")

    session_prefix = uuid.uuid4().hex[:8]
    input_path = f"temp_in_{session_prefix}_{file.filename}"
    output_filename = file.filename.rsplit('.', 1)[0] + ".docx"
    output_path = f"temp_out_{session_prefix}_{output_filename}"

    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    try:
        if os.path.getsize(input_path) == 0:
            raise HTTPException(status_code=400, detail="Uploaded PDF file is empty.")

        convert_pdf_to_word(input_path, output_path)
        
        if not os.path.exists(output_path):
            raise HTTPException(status_code=500, detail="Word document was not generated by engine.")

        # BackgroundTask ব্যবহার করা হয়েছে যাতে ফাইল ক্লায়েন্টে পৌঁছে যাওয়ার পর সার্ভার থেকে রিমুভ হয়ে যায়
        if background_tasks:
            background_tasks.add_task(cleanup_files, input_path, output_path)

        return FileResponse(
            output_path,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            filename=output_filename,
            headers={"Content-Disposition": f"attachment; filename={output_filename}"}
        )
    except Exception as e:
        cleanup_files(input_path, output_path)
        raise HTTPException(status_code=500, detail=f"PDF to Word Conversion pipeline error: {str(e)}")
